import * as Sharing from 'expo-sharing';
import { Paths, File } from 'expo-file-system';
import { Platform, Alert, Linking } from 'react-native';

export interface GroceryItem {
  id: string;
  name: string;
  quantity: string;
  category: string;
  checked: boolean;
  recipeNames?: string[];
}

export interface GroceryList {
  id: string;
  name: string;
  date: Date;
  items: GroceryItem[];
}

const APP_NAME = 'MealSwipe';
const APP_WEBSITE = 'mealswipe.app';

class GroceryExportService {
  
  /**
   * Format grocery list as plain text
   */
  formatAsText(list: GroceryList): string {
    const dateStr = new Date(list.date).toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    let text = `🛒 ${APP_NAME} Grocery List\n`;
    text += `📅 ${dateStr}\n`;
    text += `${'─'.repeat(40)}\n\n`;

    // Group items by category
    const categorized = this.groupByCategory(list.items);

    for (const [category, items] of Object.entries(categorized)) {
      text += `📁 ${category}\n`;
      items.forEach(item => {
        const check = item.checked ? '✅' : '⬜';
        text += `   ${check} ${item.name}`;
        if (item.quantity) text += ` (${item.quantity})`;
        text += '\n';
      });
      text += '\n';
    }

    text += `${'─'.repeat(40)}\n`;
    text += `Generated by ${APP_NAME}\n`;
    text += `Download: ${APP_WEBSITE}\n`;

    return text;
  }

  /**
   * Format as Markdown (for apps that support it)
   */
  formatAsMarkdown(list: GroceryList): string {
    const dateStr = new Date(list.date).toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    let md = `# 🛒 ${APP_NAME} Grocery List\n\n`;
    md += `**Date:** ${dateStr}\n\n---\n\n`;

    const categorized = this.groupByCategory(list.items);

    for (const [category, items] of Object.entries(categorized)) {
      md += `## ${category}\n`;
      items.forEach(item => {
        const check = item.checked ? 'x' : ' ';
        md += `- [${check}] **${item.name}**`;
        if (item.quantity) md += ` _(${item.quantity})_`;
        md += '\n';
      });
      md += '\n';
    }

    md += `---\n\n`;
    md += `_Generated by [${APP_NAME}](${APP_WEBSITE})_\n`;

    return md;
  }

  /**
   * Export to iOS Reminders app via URL scheme
   */
  async exportToReminders(list: GroceryList): Promise<boolean> {
    if (Platform.OS !== 'ios') {
      Alert.alert('Not Available', 'Reminders export is only available on iOS');
      return false;
    }

    try {
      // Create a new list in Reminders
      const dateStr = new Date(list.date).toLocaleDateString('en-US', {
        month: 'short',
        day: 'numeric',
      });
      const listName = `${APP_NAME} - ${dateStr}`;

      // Reminders URL scheme - open the app
      const reminderItems = list.items.map(item => {
        const note = item.quantity ? `(${item.quantity}) - from ${item.recipeNames?.join(', ') || APP_NAME}` : '';
        return { title: item.name, note };
      });

      // We'll use the reminders:// URL scheme to open Reminders
      // Note: iOS doesn't allow direct creation via URL scheme, but we can open it
      // and copy the list to clipboard for easy pasting
      
      const text = this.formatAsText(list);
      
      Alert.alert(
        'Export to Reminders',
        'Your grocery list has been copied to the clipboard!\n\nOpen Reminders and paste to create a new list.',
        [
          { text: 'Copy & Open Reminders', onPress: async () => {
            // Copy to clipboard would go here
            const canOpen = await Linking.canOpenURL('x-apple-reminderkit://');
            if (canOpen) {
              Linking.openURL('x-apple-reminderkit://');
            }
          }},
          { text: 'Cancel', style: 'cancel' },
        ]
      );

      return true;
    } catch (error) {
      console.error('Error exporting to Reminders:', error);
      return false;
    }
  }

  /**
   * Export to iOS Notes app via URL scheme
   */
  async exportToNotes(list: GroceryList): Promise<boolean> {
    if (Platform.OS !== 'ios') {
      Alert.alert('Not Available', 'Notes export is only available on iOS');
      return false;
    }

    try {
      const text = this.formatAsText(list);
      const dateStr = new Date(list.date).toLocaleDateString('en-US', {
        month: 'short',
        day: 'numeric',
      });
      
      // Notes URL scheme
      const title = `${APP_NAME}%20Grocery%20List%20-%20${dateStr}`;
      const body = encodeURIComponent(text);
      const url = `mobilenotes://create?title=${title}&body=${body}`;

      const canOpen = await Linking.canOpenURL(url);
      if (canOpen) {
        await Linking.openURL(url);
        return true;
      }

      // Fallback: copy to clipboard and open Notes
      Alert.alert(
        'Export to Notes',
        'Your grocery list has been copied! Opening Notes...',
        [{ text: 'OK', onPress: () => Linking.openURL('mobilenotes://') }]
      );

      return true;
    } catch (error) {
      console.error('Error exporting to Notes:', error);
      return false;
    }
  }

  /**
   * Export to Apple Reminders via Share Sheet
   */
  async shareAsText(list: GroceryList): Promise<boolean> {
    try {
      const text = this.formatAsText(list);
      const dateStr = new Date(list.date).toLocaleDateString('en-US', {
        month: 'short',
        day: 'numeric',
      });
      const fileName = `${APP_NAME}_GroceryList_${dateStr.replace(/ /g, '_')}.txt`;
      const file = new File(Paths.cache, fileName);

      // Write to file
      await file.write(text);

      // Check if sharing is available
      const isAvailable = await Sharing.isAvailableAsync();
      if (!isAvailable) {
        Alert.alert('Error', 'Sharing is not available on this device');
        return false;
      }

      // Share the file
      await Sharing.shareAsync(file.uri, {
        mimeType: 'text/plain',
        dialogTitle: `${APP_NAME} Grocery List`,
        UTI: 'public.plain-text',
      });

      return true;
    } catch (error) {
      console.error('Error sharing grocery list:', error);
      return false;
    }
  }

  /**
   * Export to AnyList (popular grocery app)
   */
  async exportToAnyList(list: GroceryList): Promise<boolean> {
    try {
      const items = list.items.map(item => item.name).join('\n');
      const url = `anylist://addItems?items=${encodeURIComponent(items)}`;

      const canOpen = await Linking.canOpenURL(url);
      if (canOpen) {
        await Linking.openURL(url);
        return true;
      }

      Alert.alert(
        'AnyList Not Installed',
        'Would you like to download AnyList from the App Store?',
        [
          { text: 'Download', onPress: () => Linking.openURL('itms-apps://itunes.apple.com/app/anylist/id522396218') },
          { text: 'Cancel', style: 'cancel' },
        ]
      );

      return false;
    } catch (error) {
      console.error('Error exporting to AnyList:', error);
      return false;
    }
  }

  /**
   * Export to Todoist
   */
  async exportToTodoist(list: GroceryList): Promise<boolean> {
    try {
      const dateStr = new Date(list.date).toLocaleDateString('en-US', {
        month: 'short',
        day: 'numeric',
      });
      const projectName = `${APP_NAME}%20-%20${dateStr}`;
      
      // Todoist URL scheme
      const url = `todoist://addproject?name=${projectName}`;

      const canOpen = await Linking.canOpenURL(url);
      if (canOpen) {
        await Linking.openURL(url);
        return true;
      }

      Alert.alert(
        'Todoist Not Installed',
        'Would you like to download Todoist from the App Store?',
        [
          { text: 'Download', onPress: () => Linking.openURL('itms-apps://itunes.apple.com/app/todoist/id286345667') },
          { text: 'Cancel', style: 'cancel' },
        ]
      );

      return false;
    } catch (error) {
      console.error('Error exporting to Todoist:', error);
      return false;
    }
  }

  /**
   * Export to Things 3
   */
  async exportToThings(list: GroceryList): Promise<boolean> {
    try {
      const dateStr = new Date(list.date).toLocaleDateString('en-US', {
        month: 'short',
        day: 'numeric',
      });
      
      // Things URL scheme - create a project with to-dos
      const projectTitle = `${APP_NAME} Grocery List - ${dateStr}`;
      const toDos = list.items.map(item => {
        let toDo = item.name;
        if (item.quantity) toDo += ` (${item.quantity})`;
        return encodeURIComponent(toDo);
      }).join('&to-dos=');

      const url = `things:///add-project?title=${encodeURIComponent(projectTitle)}&to-dos=${toDos}`;

      const canOpen = await Linking.canOpenURL(url);
      if (canOpen) {
        await Linking.openURL(url);
        return true;
      }

      Alert.alert(
        'Things Not Installed',
        'Would you like to download Things from the App Store?',
        [
          { text: 'Download', onPress: () => Linking.openURL('itms-apps://itunes.apple.com/app/things-3/id904237743') },
          { text: 'Cancel', style: 'cancel' },
        ]
      );

      return false;
    } catch (error) {
      console.error('Error exporting to Things:', error);
      return false;
    }
  }

  /**
   * Copy to clipboard with formatted text
   */
  async copyToClipboard(list: GroceryList): Promise<void> {
    const text = this.formatAsText(list);
    // In React Native, you'd use Clipboard.setString(text)
    // For now, we'll share it
    await this.shareAsText(list);
  }

  /**
   * Show export options sheet
   */
  async showExportOptions(list: GroceryList): Promise<void> {
    const options = [
      { label: '📝 Notes App', action: () => this.exportToNotes(list) },
      { label: '📋 Reminders App', action: () => this.exportToReminders(list) },
      { label: '✅ Things 3', action: () => this.exportToThings(list) },
      { label: '✓ Todoist', action: () => this.exportToTodoist(list) },
      { label: '🛒 AnyList', action: () => this.exportToAnyList(list) },
      { label: '📤 Share/Export File', action: () => this.shareAsText(list) },
      { label: 'Cancel', style: 'cancel' as const },
    ];

    const labels = options.map(o => o.label);

    Alert.alert(
      'Export Grocery List',
      'Choose where to export your list:',
      labels.map((label, index) => ({
        text: label,
        style: options[index].style || 'default',
        onPress: () => {
          if (options[index].action) {
            options[index].action();
          }
        },
      }))
    );
  }

  /**
   * Group items by category
   */
  private groupByCategory(items: GroceryItem[]): Record<string, GroceryItem[]> {
    return items.reduce((acc, item) => {
      const category = item.category || 'Other';
      if (!acc[category]) acc[category] = [];
      acc[category].push(item);
      return acc;
    }, {} as Record<string, GroceryItem[]>);
  }
}

export const groceryExportService = new GroceryExportService();
