export type MealType = 'breakfast' | 'lunch' | 'dinner' | 'snack' | 'dessert' | 'drink';

export type Recipe = {
  id: string;
  name: string;
  description: string;
  image: string;
  prepTime: number;
  calories: number;
  rating: number;
  mealType: MealType;
  tags: string[];
  appliances: string[];
};

// Helper to auto-detect meal type from tags
function detectMealType(tags: string[]): MealType {
  const lowerTags = tags.map(t => t.toLowerCase());
  if (lowerTags.some(t => ['breakfast', 'brunch', 'morning'].includes(t))) return 'breakfast';
  if (lowerTags.some(t => ['lunch', 'sandwich', 'salad', 'wrap'].includes(t))) return 'lunch';
  if (lowerTags.some(t => ['dessert', 'sweet', 'cake', 'cookie', 'baking'].includes(t))) return 'dessert';
  if (lowerTags.some(t => ['snack', 'appetizer', 'dip', 'finger food'].includes(t))) return 'snack';
  if (lowerTags.some(t => ['smoothie', 'drink', 'beverage', 'cocktail'].includes(t))) return 'drink';
  return 'dinner'; // default
}

export const RECIPES: Recipe[] = [
  // ==================== BREAKFAST ====================
  {
    id: '1',
    name: 'Classic Eggs Benedict',
    description: 'Poached eggs on English muffins with Canadian bacon and hollandaise.',
    image: 'https://images.unsplash.com/photo-1608039829572-9b0d7d7e0b9c?auto=format&fit=crop&w=1600&q=80',
    prepTime: 30,
    calories: 540,
    rating: 4.7,
    tags: ['Breakfast', 'Brunch', 'Classic'],
    mealType: 'breakfast',
    appliances: ['stovetop'],
  },
  {
    id: '2',
    name: 'Fluffy Blueberry Pancakes',
    description: 'Buttermilk pancakes loaded with fresh blueberries and maple syrup.',
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 450,
    rating: 4.8,
    tags: ['Breakfast', 'Sweet', 'Weekend'],
    mealType: 'breakfast',
    appliances: ['stovetop'],
  },
  {
    id: '3',
    name: 'Avocado Toast Supreme',
    description: 'Smashed avocado on sourdough with poached egg and everything seasoning.',
    image: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?auto=format&fit=crop&w=1600&q=80',
    prepTime: 10,
    calories: 380,
    rating: 4.5,
    tags: ['Breakfast', 'Healthy', 'Quick'],
    mealType: 'breakfast',
    appliances: ['toaster-oven', 'stovetop'],
  },
  {
    id: '4',
    name: 'Açaí Bowl',
    description: 'Creamy açaí blend topped with granola, berries, and honey.',
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?auto=format&fit=crop&w=1600&q=80',
    prepTime: 10,
    calories: 420,
    rating: 4.6,
    tags: ['Breakfast', 'Healthy', 'Vegan'],
    mealType: 'breakfast',
    appliances: ['blender'],
  },
  {
    id: '5',
    name: 'French Toast',
    description: 'Thick-cut brioche dipped in cinnamon custard, pan-fried golden.',
    image: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&w=1600&q=80',
    prepTime: 15,
    calories: 480,
    rating: 4.7,
    tags: ['Breakfast', 'Sweet', 'Comfort'],
    mealType: 'breakfast',
    appliances: ['stovetop'],
  },
  {
    id: '6',
    name: 'Veggie Omelette',
    description: 'Fluffy three-egg omelette with spinach, tomatoes, and feta.',
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1600&q=80',
    prepTime: 12,
    calories: 320,
    rating: 4.4,
    tags: ['Breakfast', 'Healthy', 'Vegetarian'],
    mealType: 'breakfast',
    appliances: ['stovetop'],
  },
  {
    id: '7',
    name: 'Overnight Oats',
    description: 'Creamy oats soaked with chia, almond milk, and fresh berries.',
    image: 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?auto=format&fit=crop&w=1600&q=80',
    prepTime: 5,
    calories: 350,
    rating: 4.3,
    tags: ['Breakfast', 'Meal Prep', 'Healthy'],
    mealType: 'breakfast',
    appliances: [],
  },
  {
    id: '8',
    name: 'Breakfast Burrito',
    description: 'Scrambled eggs, chorizo, cheese, and salsa in a warm tortilla.',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=1600&q=80',
    prepTime: 15,
    calories: 580,
    rating: 4.6,
    tags: ['Breakfast', 'Mexican', 'Filling'],
    mealType: 'breakfast',
    appliances: ['stovetop'],
  },
  {
    id: '9',
    name: 'Green Smoothie Bowl',
    description: 'Spinach, banana, and mango blended with coconut milk.',
    image: 'https://images.unsplash.com/photo-1638176066666-ffb2f013c7dd?auto=format&fit=crop&w=1600&q=80',
    prepTime: 5,
    calories: 320,
    rating: 4.4,
    tags: ['Breakfast', 'Healthy', 'Vegan'],
    mealType: 'breakfast',
    appliances: ['blender'],
  },
  {
    id: '10',
    name: 'Belgian Waffles',
    description: 'Crispy waffles with whipped cream and fresh strawberries.',
    image: 'https://images.unsplash.com/photo-1562376552-0d160a2f238d?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 520,
    rating: 4.7,
    tags: ['Breakfast', 'Sweet', 'Weekend'],
    mealType: 'breakfast',
    appliances: ['stovetop'],
  },
  {
    id: '11',
    name: 'Shakshuka',
    description: 'Eggs poached in spiced tomato sauce with peppers and onions.',
    image: 'https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 340,
    rating: 4.6,
    tags: ['Breakfast', 'Mediterranean', 'Vegetarian'],
    mealType: 'breakfast',
    appliances: ['stovetop'],
  },
  {
    id: '12',
    name: 'Granola Parfait',
    description: 'Layers of Greek yogurt, crunchy granola, and mixed berries.',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1600&q=80',
    prepTime: 5,
    calories: 380,
    rating: 4.3,
    tags: ['Breakfast', 'Quick', 'Healthy'],
    mealType: 'breakfast',
    appliances: [],
  },
  {
    id: '13',
    name: 'Breakfast Hash',
    description: 'Crispy potatoes with peppers, onions, and a fried egg on top.',
    image: 'https://images.unsplash.com/photo-1513442542250-854d436a73f2?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 420,
    rating: 4.5,
    tags: ['Breakfast', 'Comfort', 'Filling'],
    mealType: 'breakfast',
    appliances: ['stovetop'],
  },
  {
    id: '14',
    name: 'Croissant Sandwich',
    description: 'Buttery croissant with ham, Swiss cheese, and Dijon mustard.',
    image: 'https://images.unsplash.com/photo-1550507992-eb63ffee0847?auto=format&fit=crop&w=1600&q=80',
    prepTime: 10,
    calories: 450,
    rating: 4.4,
    tags: ['Breakfast', 'French', 'Quick'],
    mealType: 'breakfast',
    appliances: ['toaster-oven'],
  },
  {
    id: '15',
    name: 'Chilaquiles',
    description: 'Crispy tortilla chips in salsa verde with eggs and crema.',
    image: 'https://images.unsplash.com/photo-1653501274892-3c4b0aaa86d0?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 480,
    rating: 4.6,
    tags: ['Breakfast', 'Mexican', 'Comfort'],
    mealType: 'breakfast',
    appliances: ['stovetop'],
  },

  // ==================== LUNCH ====================
  {
    id: '16',
    name: 'Caesar Salad',
    description: 'Crisp romaine with parmesan, croutons, and creamy Caesar dressing.',
    image: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&w=1600&q=80',
    prepTime: 15,
    calories: 380,
    rating: 4.5,
    tags: ['Lunch', 'Salad', 'Classic'],
    mealType: 'lunch',
    appliances: [],
  },
  {
    id: '17',
    name: 'Chicken Wrap',
    description: 'Grilled chicken with lettuce, tomato, and ranch in a flour tortilla.',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=1600&q=80',
    prepTime: 15,
    calories: 420,
    rating: 4.4,
    tags: ['Lunch', 'Quick', 'Healthy'],
    mealType: 'lunch',
    appliances: ['stovetop'],
  },
  {
    id: '18',
    name: 'Buddha Bowl',
    description: 'Quinoa, roasted chickpeas, veggies, and tahini dressing.',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 450,
    rating: 4.6,
    tags: ['Lunch', 'Vegan', 'Healthy'],
    mealType: 'lunch',
    appliances: ['oven', 'stovetop'],
  },
  {
    id: '19',
    name: 'Grilled Cheese & Tomato Soup',
    description: 'Classic combo of melty cheese sandwich and creamy tomato soup.',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 520,
    rating: 4.7,
    tags: ['Lunch', 'Comfort', 'Classic'],
    mealType: 'lunch',
    appliances: ['stovetop'],
  },
  {
    id: '20',
    name: 'Caprese Sandwich',
    description: 'Fresh mozzarella, tomatoes, basil, and balsamic on ciabatta.',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=1600&q=80',
    prepTime: 10,
    calories: 380,
    rating: 4.5,
    tags: ['Lunch', 'Italian', 'Vegetarian'],
    mealType: 'lunch',
    appliances: [],
  },
  {
    id: '21',
    name: 'Poke Bowl',
    description: 'Fresh ahi tuna over rice with avocado, edamame, and ponzu.',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 480,
    rating: 4.7,
    tags: ['Lunch', 'Japanese', 'Healthy'],
    mealType: 'lunch',
    appliances: ['rice-cooker'],
  },
  {
    id: '22',
    name: 'Club Sandwich',
    description: 'Triple-decker with turkey, bacon, lettuce, and tomato.',
    image: 'https://images.unsplash.com/photo-1567234669003-dce7a7a88821?auto=format&fit=crop&w=1600&q=80',
    prepTime: 15,
    calories: 580,
    rating: 4.5,
    tags: ['Lunch', 'Classic', 'Filling'],
    mealType: 'lunch',
    appliances: ['toaster-oven'],
  },
  {
    id: '23',
    name: 'Mediterranean Wrap',
    description: 'Hummus, falafel, cucumber, tomato, and tzatziki in a pita.',
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=1600&q=80',
    prepTime: 15,
    calories: 420,
    rating: 4.6,
    tags: ['Lunch', 'Mediterranean', 'Vegetarian'],
    mealType: 'lunch',
    appliances: [],
  },
  {
    id: '24',
    name: 'Cobb Salad',
    description: 'Greens topped with chicken, bacon, egg, avocado, and blue cheese.',
    image: 'https://images.unsplash.com/photo-1512852939750-1305098529bf?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 520,
    rating: 4.6,
    tags: ['Lunch', 'Salad', 'High Protein'],
    mealType: 'lunch',
    appliances: ['stovetop'],
  },
  {
    id: '25',
    name: 'Ramen',
    description: 'Rich pork broth with noodles, soft egg, chashu, and nori.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=1600&q=80',
    prepTime: 30,
    calories: 580,
    rating: 4.8,
    tags: ['Lunch', 'Japanese', 'Comfort'],
    mealType: 'lunch',
    appliances: ['stovetop'],
  },
  {
    id: '26',
    name: 'BLT Sandwich',
    description: 'Crispy bacon, fresh lettuce, and tomato on toasted bread with mayo.',
    image: 'https://images.unsplash.com/photo-1619096252214-ef06c45683e3?auto=format&fit=crop&w=1600&q=80',
    prepTime: 10,
    calories: 420,
    rating: 4.4,
    tags: ['Lunch', 'Classic', 'Quick'],
    mealType: 'lunch',
    appliances: ['stovetop', 'toaster-oven'],
  },
  {
    id: '27',
    name: 'Chicken Noodle Soup',
    description: 'Comforting soup with tender chicken, vegetables, and egg noodles.',
    image: 'https://images.unsplash.com/photo-1604152135912-04a022e23696?auto=format&fit=crop&w=1600&q=80',
    prepTime: 35,
    calories: 320,
    rating: 4.6,
    tags: ['Lunch', 'Comfort', 'Soup'],
    mealType: 'lunch',
    appliances: ['stovetop'],
  },
  {
    id: '28',
    name: 'Greek Salad',
    description: 'Cucumbers, tomatoes, olives, red onion, and feta with olive oil.',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=1600&q=80',
    prepTime: 10,
    calories: 280,
    rating: 4.4,
    tags: ['Lunch', 'Mediterranean', 'Healthy'],
    mealType: 'lunch',
    appliances: [],
  },
  {
    id: '29',
    name: 'Bánh Mì',
    description: 'Vietnamese baguette with pork, pickled veggies, and cilantro.',
    image: 'https://images.unsplash.com/photo-1600454021042-f04d1b70e65e?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 480,
    rating: 4.7,
    tags: ['Lunch', 'Vietnamese', 'Sandwich'],
    mealType: 'lunch',
    appliances: ['stovetop'],
  },
  {
    id: '30',
    name: 'Quinoa Salad',
    description: 'Fluffy quinoa with roasted vegetables, feta, and lemon vinaigrette.',
    image: 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 380,
    rating: 4.5,
    tags: ['Lunch', 'Healthy', 'Vegetarian'],
    mealType: 'lunch',
    appliances: ['stovetop', 'oven'],
  },

  // ==================== DINNER - CHICKEN ====================
  {
    id: '31',
    name: 'Herb Roasted Chicken',
    description: 'Juicy whole chicken with herbs, lemon, and roasted vegetables.',
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?auto=format&fit=crop&w=1600&q=80',
    prepTime: 60,
    calories: 520,
    rating: 4.8,
    tags: ['Dinner', 'Classic', 'Sunday Roast'],
    mealType: 'dinner',
    appliances: ['oven'],
  },
  {
    id: '32',
    name: 'Chicken Parmesan',
    description: 'Breaded chicken cutlet with marinara and melted mozzarella.',
    image: 'https://images.unsplash.com/photo-1632778149955-e80f8ceca2e8?auto=format&fit=crop&w=1600&q=80',
    prepTime: 35,
    calories: 580,
    rating: 4.7,
    tags: ['Dinner', 'Italian', 'Comfort'],
    mealType: 'dinner',
    appliances: ['stovetop', 'oven'],
  },
  {
    id: '33',
    name: 'Chicken Stir Fry',
    description: 'Tender chicken with vegetables in a savory ginger-soy sauce.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 380,
    rating: 4.5,
    tags: ['Dinner', 'Asian', 'Quick'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '34',
    name: 'Butter Chicken',
    description: 'Creamy tomato curry with tender chicken and warm spices.',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=1600&q=80',
    prepTime: 40,
    calories: 520,
    rating: 4.8,
    tags: ['Dinner', 'Indian', 'Curry'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '35',
    name: 'Chicken Fajitas',
    description: 'Sizzling chicken with peppers, onions, and warm tortillas.',
    image: 'https://images.unsplash.com/photo-1611250188496-e966043a0629?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 480,
    rating: 4.6,
    tags: ['Dinner', 'Mexican', 'Quick'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '36',
    name: 'Crispy Air Fryer Wings',
    description: 'Perfectly crispy chicken wings with buffalo or BBQ sauce.',
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 480,
    rating: 4.7,
    tags: ['Dinner', 'Game Day', 'Air Fryer'],
    mealType: 'dinner',
    appliances: ['air-fryer'],
  },
  {
    id: '37',
    name: 'Thai Green Curry',
    description: 'Coconut curry with chicken, bamboo shoots, and Thai basil.',
    image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=1600&q=80',
    prepTime: 30,
    calories: 480,
    rating: 4.7,
    tags: ['Dinner', 'Thai', 'Curry'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '38',
    name: 'Chicken Tikka Masala',
    description: 'Grilled chicken in a rich, creamy tomato-spice sauce.',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=1600&q=80',
    prepTime: 40,
    calories: 540,
    rating: 4.8,
    tags: ['Dinner', 'Indian', 'Popular'],
    mealType: 'dinner',
    appliances: ['stovetop', 'oven'],
  },
  {
    id: '39',
    name: 'Lemon Herb Chicken',
    description: 'Pan-seared chicken breasts with lemon, garlic, and fresh herbs.',
    image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 380,
    rating: 4.5,
    tags: ['Dinner', 'Healthy', 'Quick'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '40',
    name: 'Instant Pot Chicken & Rice',
    description: 'One-pot meal with tender chicken, fluffy rice, and vegetables.',
    image: 'https://images.unsplash.com/photo-1516714435131-44d6b64dc6a2?auto=format&fit=crop&w=1600&q=80',
    prepTime: 30,
    calories: 480,
    rating: 4.6,
    tags: ['Dinner', 'Easy', 'One Pot'],
    mealType: 'dinner',
    appliances: ['instant-pot'],
  },

  // ==================== DINNER - BEEF ====================
  {
    id: '41',
    name: 'Grilled Ribeye Steak',
    description: 'Perfectly seared ribeye with herb butter and asparagus.',
    image: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 680,
    rating: 4.9,
    tags: ['Dinner', 'Steak', 'Grilling'],
    mealType: 'dinner',
    appliances: ['grill'],
  },
  {
    id: '42',
    name: 'Beef Tacos',
    description: 'Seasoned ground beef with fresh salsa, cheese, and lime crema.',
    image: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 480,
    rating: 4.7,
    tags: ['Dinner', 'Mexican', 'Quick'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '43',
    name: 'Instant Pot Beef Stew',
    description: 'Tender beef chunks with root vegetables in rich gravy.',
    image: 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?auto=format&fit=crop&w=1600&q=80',
    prepTime: 45,
    calories: 520,
    rating: 4.7,
    tags: ['Dinner', 'Comfort', 'One Pot'],
    mealType: 'dinner',
    appliances: ['instant-pot'],
  },
  {
    id: '44',
    name: 'Beef Bulgogi',
    description: 'Korean marinated beef with garlic, soy, and sesame.',
    image: 'https://images.unsplash.com/photo-1583224994076-0a73f68e3c8e?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 420,
    rating: 4.7,
    tags: ['Dinner', 'Korean', 'BBQ'],
    mealType: 'dinner',
    appliances: ['grill', 'stovetop'],
  },
  {
    id: '45',
    name: 'Spaghetti Bolognese',
    description: 'Rich meat sauce with ground beef, tomatoes, and Italian herbs.',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=1600&q=80',
    prepTime: 45,
    calories: 580,
    rating: 4.6,
    tags: ['Dinner', 'Italian', 'Pasta'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '46',
    name: 'Slow Cooker Pot Roast',
    description: 'Fall-apart tender beef with carrots, potatoes, and onions.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1600&q=80',
    prepTime: 480,
    calories: 520,
    rating: 4.8,
    tags: ['Dinner', 'Comfort', 'Slow Cooker'],
    mealType: 'dinner',
    appliances: ['slow-cooker'],
  },
  {
    id: '47',
    name: 'Beef Burrito Bowl',
    description: 'Seasoned beef over rice with beans, corn, salsa, and guacamole.',
    image: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 620,
    rating: 4.6,
    tags: ['Dinner', 'Mexican', 'Bowl'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '48',
    name: 'Philly Cheesesteak',
    description: 'Thinly sliced beef with peppers, onions, and melted provolone.',
    image: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 580,
    rating: 4.6,
    tags: ['Dinner', 'American', 'Sandwich'],
    mealType: 'lunch',
    appliances: ['stovetop'],
  },
  {
    id: '49',
    name: 'Beef Stroganoff',
    description: 'Tender beef strips in creamy mushroom sauce over egg noodles.',
    image: 'https://images.unsplash.com/photo-1504544750208-dc0358e63f7f?auto=format&fit=crop&w=1600&q=80',
    prepTime: 35,
    calories: 580,
    rating: 4.6,
    tags: ['Dinner', 'Russian', 'Comfort'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '50',
    name: 'Meatloaf',
    description: 'Classic ground beef loaf with tangy glaze and mashed potatoes.',
    image: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&w=1600&q=80',
    prepTime: 60,
    calories: 520,
    rating: 4.5,
    tags: ['Dinner', 'American', 'Comfort'],
    mealType: 'dinner',
    appliances: ['oven'],
  },

  // ==================== DINNER - SEAFOOD ====================
  {
    id: '51',
    name: 'Honey Glazed Salmon',
    description: 'Silky salmon with a sweet honey glaze and charred lemon.',
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 420,
    rating: 4.7,
    tags: ['Dinner', 'Seafood', 'Healthy'],
    mealType: 'dinner',
    appliances: ['oven'],
  },
  {
    id: '52',
    name: 'Shrimp Scampi',
    description: 'Garlic butter shrimp over linguine with white wine and lemon.',
    image: 'https://images.unsplash.com/photo-1633504581786-316c8002b1b9?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 480,
    rating: 4.7,
    tags: ['Dinner', 'Italian', 'Seafood'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '53',
    name: 'Fish Tacos',
    description: 'Crispy beer-battered fish with cabbage slaw and chipotle crema.',
    image: 'https://images.unsplash.com/photo-1512838243191-e81e8f66f1fd?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 420,
    rating: 4.6,
    tags: ['Dinner', 'Mexican', 'Seafood'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '54',
    name: 'Pad Thai',
    description: 'Rice noodles with shrimp, peanuts, and tangy tamarind sauce.',
    image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?auto=format&fit=crop&w=1600&q=80',
    prepTime: 30,
    calories: 510,
    rating: 4.7,
    tags: ['Dinner', 'Thai', 'Noodles'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '55',
    name: 'Grilled Mahi Mahi',
    description: 'Flaky white fish with mango salsa and coconut rice.',
    image: 'https://images.unsplash.com/photo-1510130387422-82bed34b37e9?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 380,
    rating: 4.6,
    tags: ['Dinner', 'Seafood', 'Grilling'],
    mealType: 'dinner',
    appliances: ['grill'],
  },
  {
    id: '56',
    name: 'Lobster Mac & Cheese',
    description: 'Creamy mac and cheese loaded with chunks of lobster meat.',
    image: 'https://images.unsplash.com/photo-1543339494-b4cd4f7ba686?auto=format&fit=crop&w=1600&q=80',
    prepTime: 35,
    calories: 680,
    rating: 4.8,
    tags: ['Dinner', 'Seafood', 'Indulgent'],
    mealType: 'dinner',
    appliances: ['stovetop', 'oven'],
  },
  {
    id: '57',
    name: 'Teriyaki Salmon',
    description: 'Glazed salmon with sweet teriyaki sauce and steamed broccoli.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 420,
    rating: 4.6,
    tags: ['Dinner', 'Japanese', 'Healthy'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '58',
    name: 'Blackened Salmon',
    description: 'Cajun-spiced salmon seared to perfection with crispy skin.',
    image: 'https://images.unsplash.com/photo-1485921325833-c519f76c4927?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 380,
    rating: 4.7,
    tags: ['Dinner', 'Cajun', 'Healthy'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '59',
    name: 'Coconut Curry Shrimp',
    description: 'Plump shrimp in creamy coconut curry with jasmine rice.',
    image: 'https://images.unsplash.com/photo-1631292784640-2b24be784d5d?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 480,
    rating: 4.6,
    tags: ['Dinner', 'Thai', 'Curry'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '60',
    name: 'Cajun Shrimp Boil',
    description: 'Spicy shrimp with corn, potatoes, and andouille sausage.',
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=1600&q=80',
    prepTime: 35,
    calories: 520,
    rating: 4.7,
    tags: ['Dinner', 'Cajun', 'Seafood'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },

  // ==================== DINNER - PASTA ====================
  {
    id: '61',
    name: 'Spaghetti Carbonara',
    description: 'Creamy egg sauce with crispy pancetta and parmesan.',
    image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 580,
    rating: 4.8,
    tags: ['Dinner', 'Italian', 'Pasta'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '62',
    name: 'Creamy Pesto Gnocchi',
    description: 'Pillowy gnocchi tossed in basil pesto and a light cream sauce.',
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 520,
    rating: 4.7,
    tags: ['Dinner', 'Italian', 'Vegetarian'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '63',
    name: 'Fettuccine Alfredo',
    description: 'Silky pasta in rich parmesan cream sauce.',
    image: 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 620,
    rating: 4.6,
    tags: ['Dinner', 'Italian', 'Comfort'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '64',
    name: 'Lasagna',
    description: 'Layers of pasta, meat sauce, ricotta, and melted mozzarella.',
    image: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?auto=format&fit=crop&w=1600&q=80',
    prepTime: 60,
    calories: 680,
    rating: 4.8,
    tags: ['Dinner', 'Italian', 'Comfort'],
    mealType: 'dinner',
    appliances: ['oven', 'stovetop'],
  },
  {
    id: '65',
    name: 'Cacio e Pepe',
    description: 'Simple Roman pasta with pecorino cheese and black pepper.',
    image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1600&q=80',
    prepTime: 15,
    calories: 480,
    rating: 4.6,
    tags: ['Dinner', 'Italian', 'Quick'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '66',
    name: 'Penne Arrabbiata',
    description: 'Spicy tomato sauce with garlic, chili, and fresh basil.',
    image: 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 420,
    rating: 4.5,
    tags: ['Dinner', 'Italian', 'Spicy'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '67',
    name: 'Mushroom Risotto',
    description: 'Creamy arborio rice with wild mushrooms and parmesan.',
    image: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?auto=format&fit=crop&w=1600&q=80',
    prepTime: 35,
    calories: 480,
    rating: 4.7,
    tags: ['Dinner', 'Italian', 'Vegetarian'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '68',
    name: 'Baked Ziti',
    description: 'Pasta baked with ricotta, meat sauce, and melted cheese.',
    image: 'https://images.unsplash.com/photo-1633337474564-1d9478ca4e2e?auto=format&fit=crop&w=1600&q=80',
    prepTime: 45,
    calories: 580,
    rating: 4.6,
    tags: ['Dinner', 'Italian', 'Comfort'],
    mealType: 'dinner',
    appliances: ['oven', 'stovetop'],
  },
  {
    id: '69',
    name: 'Linguine with Clams',
    description: 'Fresh clams in white wine garlic sauce over linguine.',
    image: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 480,
    rating: 4.7,
    tags: ['Dinner', 'Italian', 'Seafood'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '70',
    name: 'Orecchiette with Sausage',
    description: 'Ear-shaped pasta with Italian sausage and broccoli rabe.',
    image: 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 520,
    rating: 4.5,
    tags: ['Dinner', 'Italian', 'Pasta'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },

  // ==================== DINNER - PIZZA ====================
  {
    id: '71',
    name: 'Margherita Pizza',
    description: 'San Marzano tomatoes, fresh mozzarella, and basil.',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 580,
    rating: 4.9,
    tags: ['Dinner', 'Italian', 'Pizza'],
    mealType: 'dinner',
    appliances: ['oven'],
  },
  {
    id: '72',
    name: 'Neapolitan Pizza',
    description: 'Wood-fired style pizza with charred crust and fresh toppings.',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1600&q=80',
    prepTime: 15,
    calories: 540,
    rating: 4.8,
    tags: ['Dinner', 'Italian', 'Pizza'],
    mealType: 'dinner',
    appliances: ['pizza-oven'],
  },
  {
    id: '73',
    name: 'Pepperoni Pizza',
    description: 'Classic pizza loaded with spicy pepperoni and mozzarella.',
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 620,
    rating: 4.7,
    tags: ['Dinner', 'American', 'Pizza'],
    mealType: 'dinner',
    appliances: ['oven'],
  },
  {
    id: '74',
    name: 'BBQ Chicken Pizza',
    description: 'Tangy BBQ sauce with chicken, red onion, and cilantro.',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=1600&q=80',
    prepTime: 30,
    calories: 580,
    rating: 4.6,
    tags: ['Dinner', 'American', 'Pizza'],
    mealType: 'dinner',
    appliances: ['oven'],
  },
  {
    id: '75',
    name: 'White Pizza',
    description: 'Olive oil base with ricotta, mozzarella, and fresh garlic.',
    image: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 540,
    rating: 4.5,
    tags: ['Dinner', 'Italian', 'Vegetarian'],
    mealType: 'dinner',
    appliances: ['oven'],
  },

  // ==================== DINNER - VEGETARIAN ====================
  {
    id: '76',
    name: 'Vegetable Stir Fry',
    description: 'Crisp vegetables in savory sauce with tofu over rice.',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 320,
    rating: 4.4,
    tags: ['Dinner', 'Asian', 'Vegan'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '77',
    name: 'Eggplant Parmesan',
    description: 'Breaded eggplant with marinara and melted mozzarella.',
    image: 'https://images.unsplash.com/photo-1625944525533-473f1a3d54e7?auto=format&fit=crop&w=1600&q=80',
    prepTime: 45,
    calories: 480,
    rating: 4.6,
    tags: ['Dinner', 'Italian', 'Vegetarian'],
    mealType: 'dinner',
    appliances: ['oven', 'stovetop'],
  },
  {
    id: '78',
    name: 'Black Bean Tacos',
    description: 'Spiced black beans with salsa, avocado, and lime crema.',
    image: 'https://images.unsplash.com/photo-1584208632869-05fa2b2a5934?auto=format&fit=crop&w=1600&q=80',
    prepTime: 15,
    calories: 380,
    rating: 4.5,
    tags: ['Dinner', 'Mexican', 'Vegan'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '79',
    name: 'Stuffed Bell Peppers',
    description: 'Bell peppers filled with rice, beans, and cheese.',
    image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=1600&q=80',
    prepTime: 40,
    calories: 420,
    rating: 4.5,
    tags: ['Dinner', 'Healthy', 'Vegetarian'],
    mealType: 'dinner',
    appliances: ['oven'],
  },
  {
    id: '80',
    name: 'Palak Paneer',
    description: 'Creamy spinach curry with cubes of Indian cheese.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1600&q=80',
    prepTime: 30,
    calories: 380,
    rating: 4.6,
    tags: ['Dinner', 'Indian', 'Vegetarian'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '81',
    name: 'Falafel Plate',
    description: 'Crispy falafel with hummus, tabbouleh, and warm pita.',
    image: 'https://images.unsplash.com/photo-1593001874117-c99c800e3eb5?auto=format&fit=crop&w=1600&q=80',
    prepTime: 35,
    calories: 480,
    rating: 4.6,
    tags: ['Dinner', 'Mediterranean', 'Vegan'],
    mealType: 'dinner',
    appliances: ['stovetop', 'air-fryer'],
  },
  {
    id: '82',
    name: 'Veggie Pad Thai',
    description: 'Rice noodles with tofu, vegetables, and peanut sauce.',
    image: 'https://images.unsplash.com/photo-1637806930600-37fa8892069d?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 420,
    rating: 4.5,
    tags: ['Dinner', 'Thai', 'Vegan'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '83',
    name: 'Cauliflower Curry',
    description: 'Roasted cauliflower in aromatic Indian spices and coconut milk.',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=1600&q=80',
    prepTime: 35,
    calories: 320,
    rating: 4.5,
    tags: ['Dinner', 'Indian', 'Vegan'],
    mealType: 'dinner',
    appliances: ['oven', 'stovetop'],
  },
  {
    id: '84',
    name: 'Portobello Mushroom Burger',
    description: 'Grilled portobello cap with avocado, tomato, and aioli.',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 420,
    rating: 4.4,
    tags: ['Dinner', 'Vegetarian', 'Grilling'],
    mealType: 'dinner',
    appliances: ['grill'],
  },
  {
    id: '85',
    name: 'Chana Masala',
    description: 'Spiced chickpea curry with tomatoes and warm spices.',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=1600&q=80',
    prepTime: 30,
    calories: 380,
    rating: 4.6,
    tags: ['Dinner', 'Indian', 'Vegan'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },

  // ==================== DINNER - PORK ====================
  {
    id: '86',
    name: 'Slow Cooker Pulled Pork',
    description: 'Fall-apart tender pork with tangy BBQ sauce.',
    image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=1600&q=80',
    prepTime: 480,
    calories: 450,
    rating: 4.8,
    tags: ['Dinner', 'BBQ', 'Slow Cooker'],
    mealType: 'dinner',
    appliances: ['slow-cooker'],
  },
  {
    id: '87',
    name: 'Pork Chops with Apples',
    description: 'Pan-seared chops with caramelized apples and sage.',
    image: 'https://images.unsplash.com/photo-1432139555190-58524dae6a55?auto=format&fit=crop&w=1600&q=80',
    prepTime: 30,
    calories: 480,
    rating: 4.6,
    tags: ['Dinner', 'Classic', 'Fall'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '88',
    name: 'Tonkatsu',
    description: 'Japanese breaded pork cutlet with cabbage and tonkatsu sauce.',
    image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 520,
    rating: 4.7,
    tags: ['Dinner', 'Japanese', 'Comfort'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '89',
    name: 'Carnitas',
    description: 'Crispy braised pork with salsa verde and fresh cilantro.',
    image: 'https://images.unsplash.com/photo-1613514785940-daed07799d9b?auto=format&fit=crop&w=1600&q=80',
    prepTime: 180,
    calories: 480,
    rating: 4.7,
    tags: ['Dinner', 'Mexican', 'Slow Cook'],
    mealType: 'dinner',
    appliances: ['slow-cooker', 'stovetop'],
  },
  {
    id: '90',
    name: 'Char Siu Pork',
    description: 'Chinese BBQ pork with sweet and savory glaze.',
    image: 'https://images.unsplash.com/photo-1623653387945-2fd25214f8fc?auto=format&fit=crop&w=1600&q=80',
    prepTime: 45,
    calories: 420,
    rating: 4.6,
    tags: ['Dinner', 'Chinese', 'BBQ'],
    mealType: 'dinner',
    appliances: ['oven'],
  },

  // ==================== SIDES ====================
  {
    id: '91',
    name: 'Garlic Mashed Potatoes',
    description: 'Creamy potatoes with roasted garlic and butter.',
    image: 'https://images.unsplash.com/photo-1585672840563-f2af2ced55c9?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 280,
    rating: 4.6,
    tags: ['Side', 'Comfort', 'Classic'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '92',
    name: 'Perfect Jasmine Rice',
    description: 'Fluffy, fragrant jasmine rice every time.',
    image: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 210,
    rating: 4.3,
    tags: ['Side', 'Asian', 'Basic'],
    mealType: 'dinner',
    appliances: ['rice-cooker'],
  },
  {
    id: '93',
    name: 'Roasted Brussels Sprouts',
    description: 'Crispy sprouts with balsamic glaze and bacon.',
    image: 'https://images.unsplash.com/photo-1438557068880-c5f474830377?auto=format&fit=crop&w=1600&q=80',
    prepTime: 30,
    calories: 180,
    rating: 4.5,
    tags: ['Side', 'Healthy', 'Roasted'],
    mealType: 'dinner',
    appliances: ['oven'],
  },
  {
    id: '94',
    name: 'Air Fryer French Fries',
    description: 'Crispy golden fries with minimal oil.',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 220,
    rating: 4.6,
    tags: ['Side', 'Air Fryer', 'Quick'],
    mealType: 'dinner',
    appliances: ['air-fryer'],
  },
  {
    id: '95',
    name: 'Coleslaw',
    description: 'Crunchy cabbage slaw with creamy dressing.',
    image: 'https://images.unsplash.com/photo-1625938145744-e380515399bf?auto=format&fit=crop&w=1600&q=80',
    prepTime: 10,
    calories: 150,
    rating: 4.2,
    tags: ['Side', 'BBQ', 'No Cook'],
    mealType: 'dinner',
    appliances: [],
  },
  {
    id: '96',
    name: 'Grilled Corn on the Cob',
    description: 'Sweet corn with herb butter and lime.',
    image: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=1600&q=80',
    prepTime: 15,
    calories: 180,
    rating: 4.5,
    tags: ['Side', 'Summer', 'Grilling'],
    mealType: 'dinner',
    appliances: ['grill'],
  },
  {
    id: '97',
    name: 'Mac and Cheese',
    description: 'Creamy cheese sauce with elbow macaroni.',
    image: 'https://images.unsplash.com/photo-1543339494-b4cd4f7ba686?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 480,
    rating: 4.7,
    tags: ['Side', 'Comfort', 'Classic'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '98',
    name: 'Sautéed Spinach',
    description: 'Garlic spinach with lemon and olive oil.',
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=1600&q=80',
    prepTime: 8,
    calories: 80,
    rating: 4.3,
    tags: ['Side', 'Healthy', 'Quick'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '99',
    name: 'Baked Sweet Potato',
    description: 'Fluffy sweet potato with butter and cinnamon.',
    image: 'https://images.unsplash.com/photo-1596097635121-14b63a7eda7c?auto=format&fit=crop&w=1600&q=80',
    prepTime: 45,
    calories: 180,
    rating: 4.4,
    tags: ['Side', 'Healthy', 'Vegetarian'],
    mealType: 'dinner',
    appliances: ['oven'],
  },
  {
    id: '100',
    name: 'Fried Rice',
    description: 'Day-old rice stir-fried with eggs, vegetables, and soy sauce.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=1600&q=80',
    prepTime: 15,
    calories: 320,
    rating: 4.5,
    tags: ['Side', 'Asian', 'Quick'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },

  // ==================== DESSERTS ====================
  {
    id: '101',
    name: 'Tiramisu',
    description: 'Classic Italian dessert with espresso-soaked ladyfingers.',
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=1600&q=80',
    prepTime: 30,
    calories: 420,
    rating: 4.8,
    tags: ['Dessert', 'Italian', 'No Bake'],
    mealType: 'dessert',
    appliances: [],
  },
  {
    id: '102',
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate cake with molten center.',
    image: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 480,
    rating: 4.9,
    tags: ['Dessert', 'Chocolate', 'Indulgent'],
    mealType: 'dessert',
    appliances: ['oven'],
  },
  {
    id: '103',
    name: 'New York Cheesecake',
    description: 'Rich, creamy cheesecake with graham cracker crust.',
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=1600&q=80',
    prepTime: 60,
    calories: 520,
    rating: 4.7,
    tags: ['Dessert', 'Classic', 'Baking'],
    mealType: 'dessert',
    appliances: ['oven'],
  },
  {
    id: '104',
    name: 'Apple Pie',
    description: 'Classic pie with spiced apples and flaky crust.',
    image: 'https://images.unsplash.com/photo-1568571780765-9276ac8b75a7?auto=format&fit=crop&w=1600&q=80',
    prepTime: 60,
    calories: 380,
    rating: 4.7,
    tags: ['Dessert', 'American', 'Fall'],
    mealType: 'dessert',
    appliances: ['oven'],
  },
  {
    id: '105',
    name: 'Crème Brûlée',
    description: 'Silky vanilla custard with caramelized sugar top.',
    image: 'https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?auto=format&fit=crop&w=1600&q=80',
    prepTime: 45,
    calories: 380,
    rating: 4.8,
    tags: ['Dessert', 'French', 'Elegant'],
    mealType: 'dessert',
    appliances: ['oven'],
  },
  {
    id: '106',
    name: 'Chocolate Chip Cookies',
    description: 'Soft and chewy cookies loaded with chocolate chips.',
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 220,
    rating: 4.6,
    tags: ['Dessert', 'Cookies', 'Classic'],
    mealType: 'dessert',
    appliances: ['oven'],
  },
  {
    id: '107',
    name: 'Panna Cotta',
    description: 'Silky Italian cream dessert with berry compote.',
    image: 'https://images.unsplash.com/photo-1486427944544-d2c6128c6ece?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 320,
    rating: 4.6,
    tags: ['Dessert', 'Italian', 'Elegant'],
    mealType: 'dessert',
    appliances: ['stovetop'],
  },
  {
    id: '108',
    name: 'Brownies',
    description: 'Fudgy chocolate brownies with walnuts.',
    image: 'https://images.unsplash.com/photo-1564355808539-22fda35bed7e?auto=format&fit=crop&w=1600&q=80',
    prepTime: 35,
    calories: 320,
    rating: 4.6,
    tags: ['Dessert', 'Chocolate', 'Baking'],
    mealType: 'dessert',
    appliances: ['oven'],
  },
  {
    id: '109',
    name: 'Banana Split',
    description: 'Classic sundae with bananas, ice cream, and toppings.',
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=1600&q=80',
    prepTime: 10,
    calories: 580,
    rating: 4.4,
    tags: ['Dessert', 'Ice Cream', 'No Bake'],
    mealType: 'dessert',
    appliances: [],
  },
  {
    id: '110',
    name: 'Churros',
    description: 'Crispy fried dough with cinnamon sugar and chocolate sauce.',
    image: 'https://images.unsplash.com/photo-1624371414361-e670edf4898a?auto=format&fit=crop&w=1600&q=80',
    prepTime: 30,
    calories: 380,
    rating: 4.7,
    tags: ['Dessert', 'Mexican', 'Fried'],
    mealType: 'dessert',
    appliances: ['stovetop'],
  },
  {
    id: '111',
    name: 'Mochi Ice Cream',
    description: 'Chewy rice cake wrapped around creamy ice cream.',
    image: 'https://images.unsplash.com/photo-1631206616109-f7e987093571?auto=format&fit=crop&w=1600&q=80',
    prepTime: 15,
    calories: 180,
    rating: 4.5,
    tags: ['Dessert', 'Japanese', 'Ice Cream'],
    mealType: 'dessert',
    appliances: ['microwave'],
  },
  {
    id: '112',
    name: 'Lemon Bars',
    description: 'Tangy lemon curd on buttery shortbread crust.',
    image: 'https://images.unsplash.com/photo-1464305795204-6f5bbfc7fb81?auto=format&fit=crop&w=1600&q=80',
    prepTime: 45,
    calories: 280,
    rating: 4.5,
    tags: ['Dessert', 'Baking', 'Citrus'],
    mealType: 'dessert',
    appliances: ['oven'],
  },
  {
    id: '113',
    name: 'Peach Cobbler',
    description: 'Warm peaches with buttery biscuit topping.',
    image: 'https://images.unsplash.com/photo-1488477304112-4944851de03d?auto=format&fit=crop&w=1600&q=80',
    prepTime: 45,
    calories: 380,
    rating: 4.6,
    tags: ['Dessert', 'Southern', 'Summer'],
    mealType: 'dessert',
    appliances: ['oven'],
  },
  {
    id: '114',
    name: 'Flan',
    description: 'Smooth caramel custard with burnt sugar top.',
    image: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=1600&q=80',
    prepTime: 50,
    calories: 320,
    rating: 4.7,
    tags: ['Dessert', 'Mexican', 'Classic'],
    mealType: 'dessert',
    appliances: ['oven'],
  },
  {
    id: '115',
    name: 'Chocolate Mousse',
    description: 'Light and airy chocolate mousse with whipped cream.',
    image: 'https://images.unsplash.com/photo-1541783245831-57d6fb0926d3?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 380,
    rating: 4.6,
    tags: ['Dessert', 'French', 'Chocolate'],
    mealType: 'dessert',
    appliances: ['stovetop'],
  },

  // ==================== APPETIZERS & SNACKS ====================
  {
    id: '116',
    name: 'Guacamole',
    description: 'Fresh avocado dip with lime, cilantro, and jalapeño.',
    image: 'https://images.unsplash.com/photo-1615870216519-2f9fa575fa5c?auto=format&fit=crop&w=1600&q=80',
    prepTime: 10,
    calories: 180,
    rating: 4.7,
    tags: ['Appetizer', 'Mexican', 'Vegan'],
    mealType: 'snack',
    appliances: [],
  },
  {
    id: '117',
    name: 'Bruschetta',
    description: 'Toasted bread with tomatoes, basil, and balsamic.',
    image: 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?auto=format&fit=crop&w=1600&q=80',
    prepTime: 15,
    calories: 180,
    rating: 4.5,
    tags: ['Appetizer', 'Italian', 'Vegetarian'],
    mealType: 'snack',
    appliances: ['toaster-oven'],
  },
  {
    id: '118',
    name: 'Spinach Artichoke Dip',
    description: 'Creamy dip with spinach, artichokes, and cheese.',
    image: 'https://images.unsplash.com/photo-1576506295286-5cda18df43e7?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 280,
    rating: 4.6,
    tags: ['Appetizer', 'Party', 'Vegetarian'],
    mealType: 'snack',
    appliances: ['oven'],
  },
  {
    id: '119',
    name: 'Deviled Eggs',
    description: 'Classic eggs with creamy paprika-spiced filling.',
    image: 'https://images.unsplash.com/photo-1595981267035-7b04ca84a82d?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 140,
    rating: 4.4,
    tags: ['Appetizer', 'Classic', 'Party'],
    mealType: 'snack',
    appliances: ['stovetop'],
  },
  {
    id: '120',
    name: 'Caprese Skewers',
    description: 'Mozzarella, tomato, and basil on mini skewers.',
    image: 'https://images.unsplash.com/photo-1541014741259-de529411b96a?auto=format&fit=crop&w=1600&q=80',
    prepTime: 10,
    calories: 120,
    rating: 4.5,
    tags: ['Appetizer', 'Italian', 'No Cook'],
    mealType: 'snack',
    appliances: [],
  },
  {
    id: '121',
    name: 'Stuffed Mushrooms',
    description: 'Mushroom caps filled with herbed cream cheese.',
    image: 'https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 180,
    rating: 4.5,
    tags: ['Appetizer', 'Party', 'Vegetarian'],
    mealType: 'snack',
    appliances: ['oven'],
  },
  {
    id: '122',
    name: 'Spring Rolls',
    description: 'Fresh rice paper rolls with vegetables and shrimp.',
    image: 'https://images.unsplash.com/photo-1544384249-c5c25c81d6e4?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 140,
    rating: 4.5,
    tags: ['Appetizer', 'Vietnamese', 'Healthy'],
    mealType: 'snack',
    appliances: [],
  },
  {
    id: '123',
    name: 'Mozzarella Sticks',
    description: 'Crispy breaded cheese sticks with marinara.',
    image: 'https://images.unsplash.com/photo-1531749668029-2db88e4276c7?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 320,
    rating: 4.5,
    tags: ['Appetizer', 'Fried', 'Party'],
    mealType: 'snack',
    appliances: ['air-fryer'],
  },
  {
    id: '124',
    name: 'Hummus Platter',
    description: 'Creamy chickpea dip with pita and vegetables.',
    image: 'https://images.unsplash.com/photo-1577805947697-89e18249d767?auto=format&fit=crop&w=1600&q=80',
    prepTime: 10,
    calories: 220,
    rating: 4.6,
    tags: ['Appetizer', 'Mediterranean', 'Vegan'],
    mealType: 'snack',
    appliances: ['blender'],
  },
  {
    id: '125',
    name: 'Nachos Supreme',
    description: 'Loaded tortilla chips with cheese, beans, and toppings.',
    image: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?auto=format&fit=crop&w=1600&q=80',
    prepTime: 15,
    calories: 580,
    rating: 4.6,
    tags: ['Appetizer', 'Mexican', 'Party'],
    mealType: 'snack',
    appliances: ['oven'],
  },
  {
    id: '126',
    name: 'Popcorn Shrimp',
    description: 'Bite-sized crispy shrimp with cocktail sauce.',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 280,
    rating: 4.5,
    tags: ['Appetizer', 'Seafood', 'Fried'],
    mealType: 'snack',
    appliances: ['air-fryer'],
  },
  {
    id: '127',
    name: 'Edamame',
    description: 'Steamed soybeans with sea salt.',
    image: 'https://images.unsplash.com/photo-1564894809611-1742fc40ed80?auto=format&fit=crop&w=1600&q=80',
    prepTime: 8,
    calories: 120,
    rating: 4.3,
    tags: ['Appetizer', 'Japanese', 'Healthy'],
    mealType: 'snack',
    appliances: ['microwave'],
  },
  {
    id: '128',
    name: 'Bacon-Wrapped Dates',
    description: 'Sweet dates stuffed with goat cheese, wrapped in bacon.',
    image: 'https://images.unsplash.com/photo-1541529086526-db283c563270?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 220,
    rating: 4.7,
    tags: ['Appetizer', 'Party', 'Sweet-Savory'],
    mealType: 'dessert',
    appliances: ['oven'],
  },
  {
    id: '129',
    name: 'Gyoza',
    description: 'Pan-fried Japanese dumplings with dipping sauce.',
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 220,
    rating: 4.6,
    tags: ['Appetizer', 'Japanese', 'Dumplings'],
    mealType: 'snack',
    appliances: ['stovetop'],
  },
  {
    id: '130',
    name: 'Cheese Board',
    description: 'Assorted cheeses with crackers, fruits, and nuts.',
    image: 'https://images.unsplash.com/photo-1505575967455-40e256f73376?auto=format&fit=crop&w=1600&q=80',
    prepTime: 15,
    calories: 420,
    rating: 4.6,
    tags: ['Appetizer', 'Party', 'No Cook'],
    mealType: 'snack',
    appliances: [],
  },

  // ==================== DRINKS & SMOOTHIES ====================
  {
    id: '131',
    name: 'Mango Smoothie',
    description: 'Creamy mango blend with yogurt and honey.',
    image: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?auto=format&fit=crop&w=1600&q=80',
    prepTime: 5,
    calories: 220,
    rating: 4.5,
    tags: ['Drink', 'Smoothie', 'Healthy'],
    mealType: 'drink',
    appliances: ['blender'],
  },
  {
    id: '132',
    name: 'Berry Protein Shake',
    description: 'Mixed berries with protein powder and almond milk.',
    image: 'https://images.unsplash.com/photo-1553787499-6f9133860278?auto=format&fit=crop&w=1600&q=80',
    prepTime: 5,
    calories: 280,
    rating: 4.4,
    tags: ['Drink', 'Protein', 'Post-Workout'],
    mealType: 'drink',
    appliances: ['blender'],
  },
  {
    id: '133',
    name: 'Iced Matcha Latte',
    description: 'Creamy matcha over ice with oat milk.',
    image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=1600&q=80',
    prepTime: 5,
    calories: 180,
    rating: 4.5,
    tags: ['Drink', 'Coffee', 'Japanese'],
    mealType: 'drink',
    appliances: ['blender'],
  },
  {
    id: '134',
    name: 'Piña Colada',
    description: 'Tropical blend of pineapple, coconut, and rum.',
    image: 'https://images.unsplash.com/photo-1587223962930-cb7f31384c19?auto=format&fit=crop&w=1600&q=80',
    prepTime: 5,
    calories: 320,
    rating: 4.6,
    tags: ['Drink', 'Cocktail', 'Tropical'],
    mealType: 'drink',
    appliances: ['blender'],
  },
  {
    id: '135',
    name: 'Fresh Lemonade',
    description: 'Classic lemonade with fresh squeezed lemons.',
    image: 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?auto=format&fit=crop&w=1600&q=80',
    prepTime: 10,
    calories: 120,
    rating: 4.4,
    tags: ['Drink', 'Summer', 'Refreshing'],
    mealType: 'drink',
    appliances: [],
  },
  {
    id: '136',
    name: 'Hot Chocolate',
    description: 'Rich cocoa with steamed milk and marshmallows.',
    image: 'https://images.unsplash.com/photo-1517578239113-b03992dcdd25?auto=format&fit=crop&w=1600&q=80',
    prepTime: 10,
    calories: 280,
    rating: 4.6,
    tags: ['Drink', 'Winter', 'Chocolate'],
    mealType: 'drink',
    appliances: ['stovetop'],
  },
  {
    id: '137',
    name: 'Strawberry Banana Smoothie',
    description: 'Classic smoothie with strawberries, banana, and yogurt.',
    image: 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?auto=format&fit=crop&w=1600&q=80',
    prepTime: 5,
    calories: 240,
    rating: 4.6,
    tags: ['Drink', 'Smoothie', 'Breakfast'],
    mealType: 'breakfast',
    appliances: ['blender'],
  },
  {
    id: '138',
    name: 'Golden Milk',
    description: 'Warm turmeric latte with ginger and cinnamon.',
    image: 'https://images.unsplash.com/photo-1563822249366-3efb23b8e0c9?auto=format&fit=crop&w=1600&q=80',
    prepTime: 10,
    calories: 120,
    rating: 4.4,
    tags: ['Drink', 'Healthy', 'Anti-inflammatory'],
    mealType: 'drink',
    appliances: ['stovetop'],
  },
  {
    id: '139',
    name: 'Margarita',
    description: 'Classic lime margarita with salt rim.',
    image: 'https://images.unsplash.com/photo-1556855810-ac404aa91e85?auto=format&fit=crop&w=1600&q=80',
    prepTime: 5,
    calories: 220,
    rating: 4.6,
    tags: ['Drink', 'Cocktail', 'Mexican'],
    mealType: 'drink',
    appliances: ['blender'],
  },
  {
    id: '140',
    name: 'Cold Brew Coffee',
    description: 'Smooth, slow-steeped coffee served over ice.',
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=1600&q=80',
    prepTime: 720,
    calories: 5,
    rating: 4.5,
    tags: ['Drink', 'Coffee', 'No Cook'],
    mealType: 'drink',
    appliances: [],
  },

  // ==================== MORE INTERNATIONAL ====================
  {
    id: '141',
    name: 'Bibimbap',
    description: 'Korean rice bowl with vegetables, beef, and gochujang.',
    image: 'https://images.unsplash.com/photo-1553163147-622ab57be1c7?auto=format&fit=crop&w=1600&q=80',
    prepTime: 35,
    calories: 520,
    rating: 4.7,
    tags: ['Dinner', 'Korean', 'Bowl'],
    mealType: 'dinner',
    appliances: ['stovetop', 'rice-cooker'],
  },
  {
    id: '142',
    name: 'Pho',
    description: 'Vietnamese noodle soup with beef and aromatic broth.',
    image: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=1600&q=80',
    prepTime: 45,
    calories: 420,
    rating: 4.8,
    tags: ['Dinner', 'Vietnamese', 'Soup'],
    mealType: 'lunch',
    appliances: ['stovetop'],
  },
  {
    id: '143',
    name: 'Tacos al Pastor',
    description: 'Marinated pork with pineapple, cilantro, and onion.',
    image: 'https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?auto=format&fit=crop&w=1600&q=80',
    prepTime: 40,
    calories: 420,
    rating: 4.8,
    tags: ['Dinner', 'Mexican', 'Street Food'],
    mealType: 'dinner',
    appliances: ['grill', 'stovetop'],
  },
  {
    id: '144',
    name: 'Gyro Plate',
    description: 'Seasoned lamb with tzatziki, tomatoes, and pita.',
    image: 'https://images.unsplash.com/photo-1530469912745-a215c6b256ea?auto=format&fit=crop&w=1600&q=80',
    prepTime: 30,
    calories: 580,
    rating: 4.6,
    tags: ['Dinner', 'Greek', 'Mediterranean'],
    mealType: 'dinner',
    appliances: ['grill'],
  },
  {
    id: '145',
    name: 'Paella',
    description: 'Spanish rice with saffron, seafood, and chorizo.',
    image: 'https://images.unsplash.com/photo-1534080564583-6be75777b70a?auto=format&fit=crop&w=1600&q=80',
    prepTime: 45,
    calories: 620,
    rating: 4.8,
    tags: ['Dinner', 'Spanish', 'Seafood'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '146',
    name: 'Biryani',
    description: 'Aromatic basmati rice layered with spiced meat.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=1600&q=80',
    prepTime: 60,
    calories: 580,
    rating: 4.8,
    tags: ['Dinner', 'Indian', 'Rice'],
    mealType: 'dinner',
    appliances: ['stovetop', 'oven'],
  },
  {
    id: '147',
    name: 'Jerk Chicken',
    description: 'Spicy Jamaican chicken with rice and beans.',
    image: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=1600&q=80',
    prepTime: 40,
    calories: 520,
    rating: 4.7,
    tags: ['Dinner', 'Caribbean', 'Spicy'],
    mealType: 'dinner',
    appliances: ['grill', 'oven'],
  },
  {
    id: '148',
    name: 'Kung Pao Chicken',
    description: 'Spicy stir-fry with peanuts and dried chilies.',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 420,
    rating: 4.6,
    tags: ['Dinner', 'Chinese', 'Spicy'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '149',
    name: 'Moussaka',
    description: 'Greek layered eggplant casserole with meat sauce.',
    image: 'https://images.unsplash.com/photo-1626200419199-391ae4be7a41?auto=format&fit=crop&w=1600&q=80',
    prepTime: 60,
    calories: 520,
    rating: 4.6,
    tags: ['Dinner', 'Greek', 'Comfort'],
    mealType: 'dinner',
    appliances: ['oven', 'stovetop'],
  },
  {
    id: '150',
    name: 'Chicken Shawarma',
    description: 'Middle Eastern spiced chicken with garlic sauce.',
    image: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&w=1600&q=80',
    prepTime: 35,
    calories: 480,
    rating: 4.7,
    tags: ['Dinner', 'Middle Eastern', 'Street Food'],
    mealType: 'dinner',
    appliances: ['grill', 'stovetop'],
  },

  // ==================== QUICK & EASY ====================
  {
    id: '151',
    name: 'Quesadilla',
    description: 'Crispy tortilla with melted cheese and your choice of filling.',
    image: 'https://images.unsplash.com/photo-1618040996337-56904b7850b9?auto=format&fit=crop&w=1600&q=80',
    prepTime: 10,
    calories: 420,
    rating: 4.4,
    tags: ['Quick', 'Mexican', 'Easy'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '152',
    name: 'Egg Fried Rice',
    description: 'Quick fried rice with scrambled eggs and green onions.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=1600&q=80',
    prepTime: 12,
    calories: 380,
    rating: 4.5,
    tags: ['Quick', 'Asian', 'Easy'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '153',
    name: 'Tuna Melt',
    description: 'Classic tuna salad sandwich with melted cheese.',
    image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=1600&q=80',
    prepTime: 12,
    calories: 480,
    rating: 4.4,
    tags: ['Quick', 'Lunch', 'Sandwich'],
    mealType: 'lunch',
    appliances: ['toaster-oven'],
  },
  {
    id: '154',
    name: 'Instant Ramen Upgrade',
    description: 'Instant ramen elevated with egg, vegetables, and protein.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=1600&q=80',
    prepTime: 10,
    calories: 420,
    rating: 4.3,
    tags: ['Quick', 'Budget', 'Easy'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '155',
    name: 'Microwave Mug Cake',
    description: 'Single-serve chocolate cake in under 5 minutes.',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=1600&q=80',
    prepTime: 5,
    calories: 320,
    rating: 4.2,
    tags: ['Quick', 'Dessert', 'Easy'],
    mealType: 'dessert',
    appliances: ['microwave'],
  },
  {
    id: '156',
    name: 'Caprese Salad',
    description: 'Simple salad of tomatoes, mozzarella, and basil.',
    image: 'https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5?auto=format&fit=crop&w=1600&q=80',
    prepTime: 5,
    calories: 280,
    rating: 4.5,
    tags: ['Quick', 'Italian', 'No Cook'],
    mealType: 'dinner',
    appliances: [],
  },
  {
    id: '157',
    name: 'PB&J Sandwich',
    description: 'Classic peanut butter and jelly on soft bread.',
    image: 'https://images.unsplash.com/photo-1553909489-cd47e0907980?auto=format&fit=crop&w=1600&q=80',
    prepTime: 3,
    calories: 380,
    rating: 4.2,
    tags: ['Quick', 'Classic', 'Kids'],
    mealType: 'dinner',
    appliances: [],
  },
  {
    id: '158',
    name: 'Cheese Omelette',
    description: 'Simple three-egg omelette with melted cheese.',
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1600&q=80',
    prepTime: 8,
    calories: 320,
    rating: 4.4,
    tags: ['Quick', 'Breakfast', 'Easy'],
    mealType: 'breakfast',
    appliances: ['stovetop'],
  },
  {
    id: '159',
    name: 'Microwave Popcorn',
    description: 'Homemade popcorn with butter and seasonings.',
    image: 'https://images.unsplash.com/photo-1578849278619-e73505e9610f?auto=format&fit=crop&w=1600&q=80',
    prepTime: 5,
    calories: 180,
    rating: 4.3,
    tags: ['Snack', 'Quick', 'Movie Night'],
    mealType: 'snack',
    appliances: ['microwave'],
  },
  {
    id: '160',
    name: 'Ham and Cheese Sandwich',
    description: 'Classic deli sandwich with ham, cheese, and mustard.',
    image: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=1600&q=80',
    prepTime: 5,
    calories: 380,
    rating: 4.3,
    tags: ['Quick', 'Lunch', 'Easy'],
    mealType: 'lunch',
    appliances: [],
  },

  // ==================== HEALTHY & LIGHT ====================
  {
    id: '161',
    name: 'Grilled Chicken Salad',
    description: 'Mixed greens with grilled chicken, avocado, and vinaigrette.',
    image: 'https://images.unsplash.com/photo-1512852939750-1305098529bf?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 380,
    rating: 4.5,
    tags: ['Healthy', 'Salad', 'High Protein'],
    mealType: 'lunch',
    appliances: ['grill'],
  },
  {
    id: '162',
    name: 'Zucchini Noodles',
    description: 'Spiralized zucchini with marinara and parmesan.',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=1600&q=80',
    prepTime: 15,
    calories: 180,
    rating: 4.3,
    tags: ['Healthy', 'Low Carb', 'Vegetarian'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '163',
    name: 'Baked Cod with Lemon',
    description: 'Flaky white fish with lemon, herbs, and olive oil.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 220,
    rating: 4.5,
    tags: ['Healthy', 'Seafood', 'Light'],
    mealType: 'dinner',
    appliances: ['oven'],
  },
  {
    id: '164',
    name: 'Cauliflower Rice',
    description: 'Low-carb rice alternative with herbs and garlic.',
    image: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=1600&q=80',
    prepTime: 15,
    calories: 80,
    rating: 4.2,
    tags: ['Healthy', 'Low Carb', 'Keto'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '165',
    name: 'Steamed Vegetables',
    description: 'Fresh seasonal vegetables steamed with herbs.',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1600&q=80',
    prepTime: 15,
    calories: 120,
    rating: 4.2,
    tags: ['Healthy', 'Vegan', 'Side'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '166',
    name: 'Turkey Lettuce Wraps',
    description: 'Seasoned ground turkey in crisp lettuce cups.',
    image: 'https://images.unsplash.com/photo-1626200419199-391ae4be7a41?auto=format&fit=crop&w=1600&q=80',
    prepTime: 15,
    calories: 280,
    rating: 4.4,
    tags: ['Healthy', 'Low Carb', 'Quick'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '167',
    name: 'Tuna Poke Bowl',
    description: 'Fresh ahi tuna with rice, edamame, and sesame.',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 420,
    rating: 4.7,
    tags: ['Healthy', 'Japanese', 'Bowl'],
    mealType: 'dinner',
    appliances: ['rice-cooker'],
  },
  {
    id: '168',
    name: 'Veggie Sushi Rolls',
    description: 'Fresh vegetable rolls with avocado and cucumber.',
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=1600&q=80',
    prepTime: 30,
    calories: 280,
    rating: 4.5,
    tags: ['Healthy', 'Japanese', 'Vegan'],
    mealType: 'dinner',
    appliances: ['rice-cooker'],
  },
  {
    id: '169',
    name: 'Shrimp Ceviche',
    description: 'Citrus-marinated shrimp with tomatoes and cilantro.',
    image: 'https://images.unsplash.com/photo-1535399831218-d5bd36d1a6b3?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 180,
    rating: 4.6,
    tags: ['Healthy', 'Mexican', 'No Cook'],
    mealType: 'dinner',
    appliances: [],
  },
  {
    id: '170',
    name: 'Egg White Omelette',
    description: 'Light omelette with spinach, tomatoes, and feta.',
    image: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=1600&q=80',
    prepTime: 10,
    calories: 180,
    rating: 4.3,
    tags: ['Healthy', 'Breakfast', 'High Protein'],
    mealType: 'breakfast',
    appliances: ['stovetop'],
  },

  // ==================== COMFORT FOOD ====================
  {
    id: '171',
    name: 'Chicken Pot Pie',
    description: 'Creamy chicken and vegetables under flaky pastry.',
    image: 'https://images.unsplash.com/photo-1585325701165-351af92437f9?auto=format&fit=crop&w=1600&q=80',
    prepTime: 50,
    calories: 580,
    rating: 4.7,
    tags: ['Comfort', 'Classic', 'Dinner'],
    mealType: 'dinner',
    appliances: ['oven', 'stovetop'],
  },
  {
    id: '172',
    name: 'Shepherd\'s Pie',
    description: 'Savory meat filling topped with creamy mashed potatoes.',
    image: 'https://images.unsplash.com/photo-1600626333392-ce2e4d3e5e91?auto=format&fit=crop&w=1600&q=80',
    prepTime: 55,
    calories: 520,
    rating: 4.6,
    tags: ['Comfort', 'British', 'Dinner'],
    mealType: 'dinner',
    appliances: ['oven', 'stovetop'],
  },
  {
    id: '173',
    name: 'Loaded Baked Potato',
    description: 'Baked potato with sour cream, cheese, bacon, and chives.',
    image: 'https://images.unsplash.com/photo-1633436374961-09b92742047b?auto=format&fit=crop&w=1600&q=80',
    prepTime: 60,
    calories: 480,
    rating: 4.5,
    tags: ['Comfort', 'Side', 'Vegetarian'],
    mealType: 'dinner',
    appliances: ['oven'],
  },
  {
    id: '174',
    name: 'Tater Tot Casserole',
    description: 'Creamy beef casserole topped with crispy tater tots.',
    image: 'https://images.unsplash.com/photo-1633436374961-09b92742047b?auto=format&fit=crop&w=1600&q=80',
    prepTime: 45,
    calories: 580,
    rating: 4.4,
    tags: ['Comfort', 'American', 'Family'],
    mealType: 'dinner',
    appliances: ['oven', 'stovetop'],
  },
  {
    id: '175',
    name: 'Chili Con Carne',
    description: 'Hearty beef chili with beans, tomatoes, and spices.',
    image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=1600&q=80',
    prepTime: 45,
    calories: 480,
    rating: 4.6,
    tags: ['Comfort', 'American', 'Spicy'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '176',
    name: 'French Onion Soup',
    description: 'Caramelized onion soup with melted Gruyère toast.',
    image: 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?auto=format&fit=crop&w=1600&q=80',
    prepTime: 50,
    calories: 380,
    rating: 4.7,
    tags: ['Comfort', 'French', 'Soup'],
    mealType: 'lunch',
    appliances: ['stovetop', 'oven'],
  },
  {
    id: '177',
    name: 'Biscuits and Gravy',
    description: 'Fluffy biscuits smothered in sausage gravy.',
    image: 'https://images.unsplash.com/photo-1513442542250-854d436a73f2?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 580,
    rating: 4.5,
    tags: ['Comfort', 'Southern', 'Breakfast'],
    mealType: 'breakfast',
    appliances: ['oven', 'stovetop'],
  },
  {
    id: '178',
    name: 'Sloppy Joes',
    description: 'Sweet and tangy ground beef on soft buns.',
    image: 'https://images.unsplash.com/photo-1619740455993-9e612b1af08a?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 480,
    rating: 4.4,
    tags: ['Comfort', 'American', 'Family'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '179',
    name: 'Chicken Fried Steak',
    description: 'Breaded steak with creamy country gravy.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1600&q=80',
    prepTime: 30,
    calories: 680,
    rating: 4.5,
    tags: ['Comfort', 'Southern', 'Dinner'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '180',
    name: 'Hot Dog',
    description: 'Classic grilled hot dog with your favorite toppings.',
    image: 'https://images.unsplash.com/photo-1612392062126-c3d7e9a1bc84?auto=format&fit=crop&w=1600&q=80',
    prepTime: 10,
    calories: 350,
    rating: 4.3,
    tags: ['Comfort', 'American', 'Quick'],
    mealType: 'dinner',
    appliances: ['grill'],
  },

  // ==================== BURGERS ====================
  {
    id: '181',
    name: 'Classic Cheeseburger',
    description: 'Juicy beef patty with cheese, lettuce, tomato, and pickles.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 580,
    rating: 4.7,
    tags: ['Dinner', 'American', 'Grilling'],
    mealType: 'dinner',
    appliances: ['grill'],
  },
  {
    id: '182',
    name: 'Bacon Burger',
    description: 'Loaded with crispy bacon, cheese, and BBQ sauce.',
    image: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 720,
    rating: 4.7,
    tags: ['Dinner', 'American', 'Indulgent'],
    mealType: 'dinner',
    appliances: ['grill'],
  },
  {
    id: '183',
    name: 'Turkey Burger',
    description: 'Lean turkey patty with avocado and sprouts.',
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 420,
    rating: 4.4,
    tags: ['Dinner', 'Healthy', 'Grilling'],
    mealType: 'dinner',
    appliances: ['grill'],
  },
  {
    id: '184',
    name: 'Veggie Burger',
    description: 'Black bean and vegetable patty with all the fixings.',
    image: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 380,
    rating: 4.4,
    tags: ['Dinner', 'Vegetarian', 'Grilling'],
    mealType: 'dinner',
    appliances: ['grill'],
  },
  {
    id: '185',
    name: 'Smash Burger',
    description: 'Thin crispy-edged patties with cheese and special sauce.',
    image: 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?auto=format&fit=crop&w=1600&q=80',
    prepTime: 15,
    calories: 620,
    rating: 4.8,
    tags: ['Dinner', 'American', 'Quick'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },

  // ==================== ASIAN FAVORITES ====================
  {
    id: '186',
    name: 'General Tso\'s Chicken',
    description: 'Crispy chicken in sweet and spicy sauce.',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=1600&q=80',
    prepTime: 30,
    calories: 520,
    rating: 4.6,
    tags: ['Dinner', 'Chinese', 'Popular'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '187',
    name: 'Orange Chicken',
    description: 'Crispy chicken bites in tangy orange glaze.',
    image: 'https://images.unsplash.com/photo-1608039755401-742074f0548d?auto=format&fit=crop&w=1600&q=80',
    prepTime: 30,
    calories: 540,
    rating: 4.6,
    tags: ['Dinner', 'Chinese', 'Sweet'],
    mealType: 'dessert',
    appliances: ['stovetop'],
  },
  {
    id: '188',
    name: 'Beef and Broccoli',
    description: 'Tender beef with broccoli in garlic sauce.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 380,
    rating: 4.5,
    tags: ['Dinner', 'Chinese', 'Quick'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '189',
    name: 'Chicken Teriyaki',
    description: 'Grilled chicken with sweet teriyaki glaze.',
    image: 'https://images.unsplash.com/photo-1609183480237-ccfec5be47bc?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 420,
    rating: 4.5,
    tags: ['Dinner', 'Japanese', 'Easy'],
    mealType: 'dinner',
    appliances: ['stovetop', 'grill'],
  },
  {
    id: '190',
    name: 'Fried Dumplings',
    description: 'Crispy pan-fried pork dumplings with dipping sauce.',
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=1600&q=80',
    prepTime: 30,
    calories: 320,
    rating: 4.6,
    tags: ['Appetizer', 'Chinese', 'Dumplings'],
    mealType: 'snack',
    appliances: ['stovetop'],
  },
  {
    id: '191',
    name: 'Miso Soup',
    description: 'Traditional soup with tofu, seaweed, and green onions.',
    image: 'https://images.unsplash.com/photo-1607301405390-d831c242f59b?auto=format&fit=crop&w=1600&q=80',
    prepTime: 15,
    calories: 80,
    rating: 4.4,
    tags: ['Soup', 'Japanese', 'Light'],
    mealType: 'lunch',
    appliances: ['stovetop'],
  },
  {
    id: '192',
    name: 'Katsu Curry',
    description: 'Crispy chicken cutlet with Japanese curry sauce.',
    image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=1600&q=80',
    prepTime: 35,
    calories: 620,
    rating: 4.7,
    tags: ['Dinner', 'Japanese', 'Comfort'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '193',
    name: 'Dan Dan Noodles',
    description: 'Spicy Sichuan noodles with minced pork.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 480,
    rating: 4.6,
    tags: ['Dinner', 'Chinese', 'Spicy'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '194',
    name: 'Mapo Tofu',
    description: 'Silken tofu in spicy Sichuan pork sauce.',
    image: 'https://images.unsplash.com/photo-1582576163090-09d3b6f8a969?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 320,
    rating: 4.5,
    tags: ['Dinner', 'Chinese', 'Spicy'],
    mealType: 'dinner',
    appliances: ['stovetop'],
  },
  {
    id: '195',
    name: 'Tom Yum Soup',
    description: 'Spicy and sour Thai soup with shrimp.',
    image: 'https://images.unsplash.com/photo-1548943487-a2e4e43b4853?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 180,
    rating: 4.6,
    tags: ['Soup', 'Thai', 'Spicy'],
    mealType: 'lunch',
    appliances: ['stovetop'],
  },

  // ==================== MORE RECIPES ====================
  {
    id: '196',
    name: 'Eggs in Purgatory',
    description: 'Eggs cooked in spicy tomato sauce with crusty bread.',
    image: 'https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=1600&q=80',
    prepTime: 20,
    calories: 320,
    rating: 4.5,
    tags: ['Breakfast', 'Italian', 'Spicy'],
    mealType: 'breakfast',
    appliances: ['stovetop'],
  },
  {
    id: '197',
    name: 'Chia Pudding',
    description: 'Creamy chia seeds in coconut milk with fruit.',
    image: 'https://images.unsplash.com/photo-1546039907-7fa05f864c02?auto=format&fit=crop&w=1600&q=80',
    prepTime: 5,
    calories: 280,
    rating: 4.3,
    tags: ['Breakfast', 'Healthy', 'No Cook'],
    mealType: 'breakfast',
    appliances: [],
  },
  {
    id: '198',
    name: 'Stuffed French Toast',
    description: 'Brioche stuffed with cream cheese and berries.',
    image: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&w=1600&q=80',
    prepTime: 25,
    calories: 580,
    rating: 4.7,
    tags: ['Breakfast', 'Indulgent', 'Brunch'],
    mealType: 'breakfast',
    appliances: ['stovetop'],
  },
  {
    id: '199',
    name: 'Elote (Mexican Street Corn)',
    description: 'Grilled corn with mayo, cotija, chili, and lime.',
    image: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=1600&q=80',
    prepTime: 15,
    calories: 280,
    rating: 4.7,
    tags: ['Side', 'Mexican', 'Grilling'],
    mealType: 'dinner',
    appliances: ['grill'],
  },
  {
    id: '200',
    name: 'Cinnamon Rolls',
    description: 'Soft, gooey rolls with cinnamon swirl and cream cheese frosting.',
    image: 'https://images.unsplash.com/photo-1609127102567-b4d7a4e1e8e0?auto=format&fit=crop&w=1600&q=80',
    prepTime: 90,
    calories: 420,
    rating: 4.8,
    tags: ['Breakfast', 'Baking', 'Sweet'],
    mealType: 'breakfast',
    appliances: ['oven'],
  },
];
